### ISSUE TITLE
Enforce a minimum rabbit allocation size

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-coral2#131]
According to Brian Behlendorf, there is a minimum allocation size for rabbits.

> The absolute minimum device size we can allow turns out to be 142,606,336 bytes.  Assuming we might use up to 18 devices for a fully populated chassis that's 2,566,914,048 bytes.  To leave ourselves some elbow room how about we put a 4G floor on the provided Allocation Size.

In general this isn't an issue if users request reasonably large file systems, but some Lustre `mdts` can end up being quite small. It seems only minimally wasteful to transform all allocation requests into >4GB requests.

**Comment by vsoch** [comment]
Ping @hariharan-devarajan and @milroy this is pretty interesting / relevant for our discussion today. When requesting resources I don't usually have the mindset to ask "Is this _too small_"?

**Comment by vsoch** [comment]
Relevant PR: https://github.com/flux-framework/flux-coral2/pull/132

**Comment by jameshcorbett** [comment]
Two things to note: rabbits have a capacity so much higher than 4GiB, this floor is pretty insignificant. And also, I wasn't thinking of rejecting small allocations, just (behind the scenes) giving the user more storage than they requested.

**Comment by vsoch** [comment]
@jameshcorbett I was thinking in the context of a jobspec that is able to request storage - it sounds like if the request is too small we would run into trouble, and maybe not every cluster has a behind the scenes solution to set a minimum in that case. So when we check to see if a jobspec can be satisfied (and is valid) we need to ensure it's not too small. And maybe if it is, and it's a global truth (meaning it would be too small for any cluster) we could tweak the jobspec on our own, kind of like a mutating 
Kubernetes webhook!

**Comment by jameshcorbett** [comment]
Yeah, I really don't know what you kind of situations you're working with, I only have a brain for the specific rabbit situation I'm dealing with. But anyway, I think a mutating Kubernetes webhook is kind of what I have here, it will modify users' jobspecs to increase the storage request. But it's a bit different, because we have to modify their jobspecs regardless of the size of the storage request they make....

**Comment by grondo** [comment]
> we could tweak the jobspec on our own, kind of like a mutating Kubernetes webhook!

Just thought I'd mention that there's a facility for doing this in flux-core called the job [frobnicator](https://flux-framework.readthedocs.io/projects/flux-core/en/stable/man5/flux-config-ingest.html#frobnicator-keys). It is mainly used for assigning jobspec defaults for now, but could be used to modify jobspec arbitrarily (though modifications to sections used by the job shell will be ignored since the job shell uses the signed J and not the modified jobspec). Not that it necessarily applies to the problem described in this issue, but it does address the larger discussion of "tweaking the jobspec before submission".
