### ISSUE TITLE
Draining rabbit nodes

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-coral2#99]
Admins will want a way to drain rabbit nodes without impacting compute-only jobs. The simplest (and currently supported) way to drain a rabbit would be to drain all the compute nodes it is associated with. But that is very inefficient, ideally jobs which don't use rabbit resources would continue to be scheduled, and only the rabbit itself would be drained.

@grondo @milroy is there a way to send an RPC to Fluxion to mark a section of the resource graph as being drained, so that it shouldn't be considered for future jobs?

**Comment by grondo** [comment]
Currently the drain semantics work by updating broker ranks as "down" to the scheduler, so this is effectively a node-only solution for now (at least I don't think you'll be able to use `flux resource drain` for this unfortunately). Also, since the rabbits are presumably configured in the scheduling part of _R_, which is opaque to all the core services, it feels like this is going to need a Fluxion only solution at first.

Maybe after we get something basic working with Fluxion we could consider how to expose non-execution target "drained" resources to core flux utilities.

To clarify, you'd like to "drain" the rabbits and not just set them "down" so that any currently running jobs on the drained rabbits are not terminated?

**Comment by jameshcorbett** [comment]
After discussion in a meeting, there is functionality in sched that does some of what we would need, e.g. https://github.com/flux-framework/flux-sched/blob/9c48feefb6f903942b7eefb674b6221d06cc5781/t/t3025-resource-find.t#L58 and https://github.com/flux-framework/flux-sched/blob/9c48feefb6f903942b7eefb674b6221d06cc5781/resource/utilities/command.cpp#L663

**Comment by jameshcorbett** [comment]
Implemented by #117.
